Repository apify/crawlee, pull requests merged in 2023-10, with the labels that each got.

#2104 fix(templates): install browsers on postinstall for playwright
  packages/cli/src/commands/InstallPlaywrightBrowsersCommand.ts
  packages/cli/src/index.ts
  packages/templates/templates/playwright-js/package.json
  packages/templates/templates/playwright-ts/package.json
Labels: adhoc, t-tooling

#2102 fix: allow to use any version of puppeteer or playwright
  package.json
  packages/browser-pool/package.json
  packages/browser-pool/src/puppeteer/puppeteer-plugin.ts
  packages/crawlee/package.json
  packages/playwright-crawler/package.json
  packages/puppeteer-crawler/package.json
  test/core/enqueue_links/click_elements.test.ts
  yarn.lock
Labels: adhoc, debt, t-tooling, tested

#2109 fix(types): re-export RequestQueueOptions as an alias to RequestProviderOptions
  packages/core/src/storages/request_provider.ts
Labels: adhoc, t-tooling

#2111 feat: add incapsula iframe selector to the blocked list
  packages/utils/src/internals/blocked.ts
Labels: t-tooling

#2114 fix: ensure the status message cannot stuck the crawler
  packages/basic-crawler/src/internals/basic-crawler.ts
Labels: adhoc, t-tooling

#2115 fix: add warning when we detect use of RL and RQ, but RQ is not provided explicitly
  packages/basic-crawler/src/internals/basic-crawler.ts
  test/core/crawlers/browser_crawler.test.ts
Labels: adhoc, t-tooling, tested

#2116 fix: RQ request count is consistent after migration
  packages/basic-crawler/src/internals/basic-crawler.ts
  packages/core/src/storages/request_provider.ts
Labels: t-tooling

#2122 fix: refactor `extractUrls` to split the text line by line first
  packages/utils/src/internals/extract-urls.ts
Labels: adhoc, t-tooling

#2118 chore: vitest
  CONTRIBUTING.md
  jest.config.js
  package.json
  packages/basic-crawler/test/migration.test.ts
  packages/basic-crawler/test/tsconfig.json
  packages/browser-crawler/test/migration.test.ts
  packages/browser-crawler/test/tsconfig.json
  packages/browser-pool/test/multiple-plugins.test.ts
  packages/browser-pool/test/tsconfig.json
  packages/cheerio-crawler/test/migration.test.ts
  packages/cheerio-crawler/test/tsconfig.json
  packages/core/test/request-queue/adding-the-same-request-should-not-call-the-api.test.ts
  packages/core/test/request-queue/request-queue-v2.test.ts
  packages/core/test/tsconfig.json
  packages/memory-storage/test/tsconfig.json
  packages/puppeteer-crawler/src/internals/enqueue-links/click-elements.ts
  packages/utils/src/internals/memory-info.ts
  packages/utils/test/tsconfig.json
  test/browser-pool/browser-plugins/plugins.test.ts
  test/browser-pool/browser-pool.test.ts
  test/core/autoscaling/snapshotter.test.ts
  test/core/browser_launchers/playwright_launcher.test.ts
  test/core/browser_launchers/puppeteer_launcher.test.ts
  test/core/crawlers/basic_crawler.test.ts
  test/core/crawlers/browser_crawler.test.ts
  test/core/crawlers/cheerio_crawler.test.ts
  test/core/crawlers/dom_crawler.test.ts
  test/core/crawlers/http_crawler.test.ts
  test/core/crawlers/playwright_crawler.test.ts
  test/core/crawlers/puppeteer_crawler.test.ts
  test/core/crawlers/statistics.test.ts
  test/core/playwright_utils.test.ts
  test/core/puppeteer_utils.test.ts
  test/core/request_list.test.ts
  test/core/router.test.ts
  test/core/session_pool/session.test.ts
  test/core/storages/dataset.test.ts
  test/core/storages/key_value_store.test.ts
  test/core/storages/request_queue.test.ts
  test/core/storages/utils.test.ts
  test/tsconfig.json
  test/utils/extract-urls.test.ts
  test/utils/general.test.ts
  test/utils/memory-info.test.ts
  tsconfig.eslint.json
  vitest.config.ts
  yarn.lock
Labels: adhoc, t-tooling, tested

#2126 chore: update playwright to 1.39
  package.json
  vitest.config.ts
  yarn.lock
Labels: adhoc, debt, t-tooling, tested

#2128 docs: downgrade docusaurus and typedoc to fix broken links in api docs
  website/package.json
  website/roa-loader/index.js
  website/yarn.lock
Labels: adhoc, t-tooling

#2127 docs: add experiments section
  docs/experiments/request_locking.mdx
  website/sidebars.js
  website/versioned_docs/version-3.5/experiments/request_locking.mdx
  website/versioned_sidebars/version-3.5-sidebars.json
Labels: adhoc, t-tooling

#2132 fix(MemoryStorage): ignore invalid files for request queues
  packages/memory-storage/src/cache-helpers.ts
  packages/memory-storage/test/request-queue/ignore-non-json-files.test.ts
Labels: t-tooling, tested

#2141 chore: make e2e pass again
  test/e2e/puppeteer-store-pagination-jquery/actor/main.js
  test/e2e/puppeteer-store-pagination-jquery/test.mjs
  test/e2e/puppeteer-store-pagination/actor/main.js
  test/e2e/puppeteer-store-pagination/test.mjs
Labels: adhoc, t-tooling, tested
