Repository apify/crawlee, pull requests merged in 2023-12, with the labels that each got.

#2227 docs: set fixed width for short docs articles
  website/src/css/custom.css
Labels: documentation, adhoc, t-tooling

#2232 docs: improve warning message on empty RequestList
  packages/core/src/storages/request_list.ts
  packages/core/src/storages/request_provider.ts
Labels: documentation, adhoc, t-tooling

#2239 fix: make SessionPool queue up getSession calls to prevent overruns
  packages/core/package.json
  packages/core/src/session_pool/session_pool.ts
  yarn.lock
Labels: t-tooling

#2214 feat: robots.txt and sitemap.xml utils
  docs/examples/crawl_sitemap.mdx
  docs/examples/crawl_sitemap_cheerio.ts
  docs/examples/crawl_sitemap_playwright.ts
  docs/examples/crawl_sitemap_puppeteer.ts
  package.json
  packages/utils/package.json
  packages/utils/src/index.ts
  packages/utils/src/internals/robots.ts
  packages/utils/src/internals/sitemap.ts
  packages/utils/test/robots.test.ts
  packages/utils/test/sitemap.test.ts
  packages/utils/tsconfig.build.json
  yarn.lock
Labels: t-tooling, tested

#2244 fix: make CLI work on Windows too with `--no-purge`
  packages/cli/src/commands/RunProjectCommand.ts
Labels: adhoc, t-tooling

#2243 fix: `retryOnBlocked` doesn't override the blocked HTTP codes
  packages/browser-crawler/src/internals/browser-crawler.ts
  packages/core/src/session_pool/consts.ts
  packages/core/src/session_pool/index.ts
  packages/core/src/session_pool/session_pool.ts
  packages/utils/src/internals/blocked.ts
  test/core/crawlers/browser_crawler.test.ts
  test/shared/_helper.ts
Labels: adhoc, t-tooling, tested

#2213 feat: allow configuring crawler statistics
  packages/basic-crawler/src/internals/basic-crawler.ts
  packages/core/src/crawlers/statistics.ts
  packages/core/src/session_pool/session_pool.ts
Labels: t-tooling

#2238 feat: check enqueue link strategy post redirect
  packages/basic-crawler/src/internals/basic-crawler.ts
  packages/browser-crawler/src/internals/browser-crawler.ts
  packages/core/src/enqueue_links/enqueue_links.ts
  packages/core/src/enqueue_links/shared.ts
  packages/core/src/request.ts
  packages/core/test/enqueue_links/add-enqueue-strategy-to-requests.ts
  packages/http-crawler/src/internals/http-crawler.ts
  test/core/crawlers/browser_crawler.test.ts
  test/core/crawlers/cheerio_crawler.test.ts
  test/shared/_helper.ts
Labels: t-tooling, tested

#2252 feat: log cause with `retryOnBlocked`
  packages/basic-crawler/src/internals/basic-crawler.ts
  packages/browser-crawler/src/internals/browser-crawler.ts
  packages/http-crawler/src/internals/http-crawler.ts
Labels: t-tooling

#2258 fix: ES2022 build compatibility and move to NodeNext for module
  packages/templates/templates/cheerio-ts/tsconfig.json
  packages/templates/templates/getting-started-ts/tsconfig.json
  packages/templates/templates/playwright-ts/tsconfig.json
  packages/templates/templates/puppeteer-ts/tsconfig.json
  packages/utils/package.json
  scripts/typescript_fixes.mjs
  yarn.lock
Labels: t-tooling
