Repository apify/crawlee, pull requests merged in 2023-09, with the labels that each got.

#2080 docs: add start:fast script for faster docs development
  website/docusaurus.config.js
  website/package.json
  website/roa-loader/index.js
Labels: adhoc, t-tooling

#2083 fix: session pool leaks memory on multiple crawler runs
  packages/basic-crawler/src/internals/basic-crawler.ts
  packages/core/src/session_pool/session_pool.ts
Labels: t-tooling

#1975 feat: Request Queue v2
  packages/basic-crawler/src/internals/basic-crawler.ts
  packages/browser-crawler/src/internals/browser-crawler.ts
  packages/cheerio-crawler/src/internals/cheerio-crawler.ts
  packages/core/src/enqueue_links/enqueue_links.ts
  packages/core/src/request.ts
  packages/core/src/storages/index.ts
  packages/core/src/storages/request_provider.ts
  packages/core/src/storages/request_queue.ts
  packages/core/src/storages/request_queue_v2.ts
  packages/core/src/storages/storage_manager.ts
  packages/core/src/storages/utils.ts
  packages/core/test/request-queue/request-queue-v2.test.ts
  packages/jsdom-crawler/src/internals/jsdom-crawler.ts
  packages/linkedom-crawler/src/internals/linkedom-crawler.ts
  packages/memory-storage/src/resource-clients/request-queue.ts
  packages/playwright-crawler/src/internals/enqueue-links/click-elements.ts
  packages/puppeteer-crawler/src/internals/enqueue-links/click-elements.ts
  test/core/storages/request_queue.test.ts
  test/e2e/cheerio-request-queue-v2/actor/.actor/actor.json
  test/e2e/cheerio-request-queue-v2/actor/.gitignore
  test/e2e/cheerio-request-queue-v2/actor/Dockerfile
  test/e2e/cheerio-request-queue-v2/actor/main.js
  test/e2e/cheerio-request-queue-v2/actor/package.json
  test/e2e/cheerio-request-queue-v2/test.mjs
Labels: tech roadmap, t-tooling, tested

#2084 docs: add AWS / GCP deployment guides
  docs/deployment/apify_platform.mdx
  docs/deployment/apify_platform_init_exit.ts
  docs/deployment/apify_platform_main.ts
  docs/deployment/aws-browsers.md
  docs/deployment/aws-cheerio.md
  docs/deployment/gcp-browsers.md
  docs/deployment/gcp-cheerio.md
  docs/guides/docker_images.mdx
  docs/introduction/08-refactoring.mdx
  docs/introduction/09-deployment.mdx
  website/docusaurus.config.js
  website/sidebars.js
  website/versioned_docs/version-3.5/deployment/apify_platform.mdx
  website/versioned_docs/version-3.5/deployment/apify_platform_init_exit.ts
  website/versioned_docs/version-3.5/deployment/apify_platform_main.ts
  website/versioned_docs/version-3.5/deployment/aws-browsers.md
  website/versioned_docs/version-3.5/deployment/aws-cheerio.md
  website/versioned_docs/version-3.5/deployment/gcp-browsers.md
  website/versioned_docs/version-3.5/deployment/gcp-cheerio.md
  website/versioned_docs/version-3.5/guides/docker_images.mdx
  website/versioned_docs/version-3.5/introduction/08-refactoring.mdx
  website/versioned_docs/version-3.5/introduction/09-deployment.mdx
  website/versioned_sidebars/version-3.5-sidebars.json
Labels: documentation, product roadmap, t-tooling

#2096 fix(types): make return type of RequestProvider.open and RequestQueue(v2).open strict and accurate
  packages/core/src/storages/request_provider.ts
  packages/core/src/storages/request_queue.ts
  packages/core/src/storages/request_queue_v2.ts
Labels: adhoc, t-tooling
