Repository apify/crawlee, pull requests merged in 2023-11, with the labels that each got.

#2155 docs: Add Arch linux instructions to contributing guide
  CONTRIBUTING.md
Labels: adhoc, t-tooling

#2157 fix: provide more detailed error messages for browser launch errors
  packages/browser-pool/src/abstract-classes/browser-plugin.ts
  packages/browser-pool/src/index.ts
  packages/browser-pool/src/playwright/playwright-plugin.ts
  packages/browser-pool/src/puppeteer/puppeteer-plugin.ts
  packages/browser-pool/test/new-errors.test.ts
Labels: adhoc, t-tooling, tested

#2154 fix: e2e cheerio-throw-on-ssl-errors
  test/e2e/cheerio-throw-on-ssl-errors/test.mjs
Labels: adhoc, t-tooling, tested

#2146 chore: update linter
  package.json
  packages/basic-crawler/src/internals/basic-crawler.ts
  packages/browser-crawler/src/internals/browser-crawler.ts
  packages/browser-pool/src/browser-pool.ts
  packages/browser-pool/src/playwright/load-firefox-addon.ts
  packages/browser-pool/src/puppeteer/puppeteer-controller.ts
  packages/browser-pool/test/multiple-plugins.test.ts
  packages/cheerio-crawler/src/internals/cheerio-crawler.ts
  packages/cli/src/commands/CreateProjectCommand.ts
  packages/core/src/autoscaling/autoscaled_pool.ts
  packages/core/src/events/event_manager.ts
  packages/core/src/storages/dataset.ts
  packages/core/src/storages/request_list.ts
  packages/core/src/storages/request_queue.ts
  packages/core/src/storages/request_queue_v2.ts
  packages/core/src/storages/storage_manager.ts
  packages/http-crawler/src/internals/http-crawler.ts
  packages/jsdom-crawler/src/internals/jsdom-crawler.ts
  packages/memory-storage/src/memory-storage.ts
  packages/memory-storage/test/no-writing-to-disk.test.ts
  packages/memory-storage/test/write-metadata.test.ts
  packages/playwright-crawler/src/internals/utils/playwright-utils.ts
  packages/puppeteer-crawler/src/internals/utils/puppeteer_utils.ts
  packages/utils/src/internals/general.ts
  test/browser-pool/browser-pool.test.ts
  test/core/autoscaling/autoscaled_pool.test.ts
  test/core/browser_launchers/playwright_launcher.test.ts
  test/core/browser_launchers/puppeteer_launcher.test.ts
  test/core/crawlers/basic_browser_crawler.ts
  test/core/crawlers/basic_crawler.test.ts
  test/core/crawlers/browser_crawler.test.ts
  test/core/crawlers/cheerio_crawler.test.ts
  test/core/crawlers/puppeteer_crawler.test.ts
  test/core/enqueue_links/click_elements.test.ts
  test/core/puppeteer_request_interception.test.ts
  test/core/storages/dataset.test.ts
  test/e2e/cheerio-default-ts/actor/main.ts
  test/e2e/jsdom-default-ts/actor/main.ts
  test/e2e/jsdom-react-ts/actor/main.ts
  test/e2e/linkedom-default-ts/actor/main.ts
  test/shared/StorageEmulator.ts
  test/shared/_helper.ts
  test/utils/general.test.ts
  test/utils/memory-info.test.ts
  yarn.lock
Labels: adhoc, debt, t-tooling, tested

#2160 chore: update yarn to v4
  package.json
  website/package.json
  website/yarn.lock
  yarn.lock
Labels: adhoc, debt, t-tooling

#2163 docs: update docusaurus to v3
  packages/http-crawler/README.md
  website/docusaurus.config.js
  website/package.json
  website/yarn.lock
Labels: adhoc, debt, t-tooling

#2165 chore: limit maxRequestsPerCrawl number in starter templates
  packages/templates/templates/cheerio-js/src/main.js
  packages/templates/templates/cheerio-ts/src/main.ts
  packages/templates/templates/getting-started-js/src/main.js
  packages/templates/templates/getting-started-ts/src/main.ts
  packages/templates/templates/playwright-js/src/main.js
  packages/templates/templates/playwright-ts/src/main.ts
  packages/templates/templates/puppeteer-js/src/main.js
  packages/templates/templates/puppeteer-ts/src/main.ts
Labels: adhoc, t-tooling

#2166 feat(core): add `crawler.exportData()` helper
  .github/workflows/test-ci.yml
  packages/basic-crawler/src/internals/basic-crawler.ts
  packages/core/src/storages/dataset.ts
  test/core/crawlers/basic_crawler.test.ts
Labels: adhoc, t-tooling, tested

#2110 feat: got-scraping ESM edition
  .eslintrc.json
  package.json
  packages/basic-crawler/package.json
  packages/basic-crawler/src/internals/basic-crawler.ts
  packages/core/src/crawlers/crawler_commons.ts
  packages/http-crawler/package.json
  packages/http-crawler/src/internals/http-crawler.ts
  packages/linkedom-crawler/src/internals/linkedom-crawler.ts
  packages/utils/package.json
  packages/utils/src/index.ts
  packages/utils/src/internals/extract-urls.ts
  packages/utils/src/internals/gotScraping.ts
  test/core/crawlers/browser_crawler.test.ts
  test/core/crawlers/cheerio_crawler.test.ts
  test/core/request_list.test.ts
  test/core/storages/request_queue.test.ts
  test/tsconfig.json
  test/utils/extract-urls.test.ts
  tsconfig.build.json
  vitest.config.ts
  yarn.lock
Labels: adhoc, t-tooling, tested

#2181 docs: responsive design fix (overflowing content)
  website/src/css/custom.css
Labels: t-tooling

#1910 feat(puppeteer): enable `new` headless mode
  packages/browser-crawler/src/internals/browser-crawler.ts
  packages/browser-pool/src/puppeteer/puppeteer-plugin.ts
  packages/playwright-crawler/src/internals/playwright-crawler.ts
  packages/puppeteer-crawler/src/internals/puppeteer-crawler.ts
  packages/puppeteer-crawler/src/internals/puppeteer-launcher.ts
  test/core/puppeteer_request_interception.test.ts
  test/core/puppeteer_utils.test.ts
  test/shared/_helper.ts
Labels: adhoc, t-tooling, tested

#2188 chore: fix cis
  .github/workflows/docs.yml
  .github/workflows/release.yml
  .github/workflows/test-ci.yml
  .github/workflows/test-e2e.yml
Labels: adhoc, t-tooling

#2192 chore: move from ts-node to tsx
  package.json
  packages/basic-crawler/package.json
  packages/browser-crawler/package.json
  packages/browser-pool/package.json
  packages/cheerio-crawler/package.json
  packages/cli/package.json
  packages/core/package.json
  packages/crawlee/package.json
  packages/http-crawler/package.json
  packages/jsdom-crawler/package.json
  packages/linkedom-crawler/package.json
  packages/memory-storage/package.json
  packages/playwright-crawler/package.json
  packages/puppeteer-crawler/package.json
  packages/templates/package.json
  packages/templates/templates/cheerio-ts/package.json
  packages/templates/templates/getting-started-ts/package.json
  packages/templates/templates/playwright-ts/package.json
  packages/templates/templates/puppeteer-ts/package.json
  packages/types/package.json
  packages/utils/package.json
  yarn.lock
Labels: adhoc, t-tooling

#2195 ci: fix release workflow and update lockfile
  .github/workflows/release.yml
  .github/workflows/test-e2e.yml
Labels: adhoc, debt, t-tooling

#2190 fix(browser-pool): respect user options before assigning fingerpints
  packages/browser-pool/src/fingerprinting/hooks.ts
  packages/browser-pool/src/utils.ts
Labels: bug

#2205 fix: filter out empty globs
  packages/core/src/enqueue_links/shared.ts
  test/core/enqueue_links/enqueue_links.test.ts
Labels: t-tooling, tested
