Repository apify/crawlee, pull requests merged in 2024-12, with the labels that each got.

#2762 docs: bump typedoc-api plugin to mitigate stray React errors
  website/package.json
  website/yarn.lock
Labels: adhoc, t-tooling

#2765 feat: add support for parsing comma-separated list environment variables
  packages/core/src/configuration.ts
Labels: adhoc, t-platform

#2776 chore: check TS in the tests and enable `strictNullChecks` in there
  .eslintrc.json
  .github/workflows/test-ci.yml
  package.json
  packages/playwright-crawler/src/internals/adaptive-playwright-crawler.ts
  test/browser-pool/browser-plugins/plugins.test.ts
  test/browser-pool/browser-pool.test.ts
  test/core/autoscaling/autoscaled_pool.test.ts
  test/core/autoscaling/snapshotter.test.ts
  test/core/browser_launchers/playwright_launcher.test.ts
  test/core/browser_launchers/puppeteer_launcher.test.ts
  test/core/crawlers/adaptive_playwright_crawler.test.ts
  test/core/crawlers/basic_crawler.test.ts
  test/core/crawlers/browser_crawler.test.ts
  test/core/crawlers/cheerio_crawler.test.ts
  test/core/crawlers/dom_crawler.test.ts
  test/core/crawlers/file_download.test.ts
  test/core/crawlers/http_crawler.test.ts
  test/core/crawlers/playwright_crawler.test.ts
  test/core/crawlers/puppeteer_crawler.test.ts
  test/core/crawlers/statistics.test.ts
  test/core/enqueue_links/click_elements.test.ts
  test/core/enqueue_links/enqueue_links.test.ts
  test/core/error_tracker.test.ts
  test/core/playwright_utils.test.ts
  test/core/proxy_configuration.test.ts
  test/core/puppeteer_request_interception.test.ts
  test/core/puppeteer_utils.test.ts
  test/core/request_list.test.ts
  test/core/session_pool/session_pool.test.ts
  test/core/sitemap_request_list.test.ts
  test/core/storages/dataset.test.ts
  test/core/storages/key_value_store.test.ts
  test/core/storages/request_queue.test.ts
  test/core/storages/utils.test.ts
  test/e2e/cheerio-curl-impersonate-ts/actor/main.ts
  test/shared/MemoryStorageEmulator.ts
  test/shared/_helper.ts
  test/tsconfig.json
  test/utils/cheerio.test.ts
  test/utils/extract-urls.test.ts
  test/utils/general.test.ts
  test/utils/memory-info.test.ts
  test/utils/social.test.ts
  website/roa-loader/index.js
Labels: adhoc, t-tooling, tested
