Repository apify/crawlee, pull requests merged in 2024-01, with the labels that each got.

#2265 chore: Move extractUrlsFromCheerio to utils
  packages/cheerio-crawler/package.json
  packages/cheerio-crawler/src/internals/cheerio-crawler.ts
  packages/core/src/enqueue_links/shared.ts
  packages/utils/src/internals/cheerio.ts
  packages/utils/src/internals/extract-urls.ts
  yarn.lock
Labels: adhoc, t-tooling

#2263 fix(RequestQueue): always clear locks when a request is reclaimed
  packages/core/src/storages/request_queue_v2.ts
Labels: t-tooling

#2219 docs: Parallel Scraping guide
  docs/guides/parallel-scraping/adapted-routes.mjs
  docs/guides/parallel-scraping/modified-detail-route.mjs
  docs/guides/parallel-scraping/parallel-scraper.mjs
  docs/guides/parallel-scraping/parallel-scraping.mdx
  docs/guides/parallel-scraping/shared.mjs
  website/roa-loader/index.js
  website/sidebars.js
  website/versioned_docs/version-3.6/guides/parallel-scraping/adapted-routes.mjs
  website/versioned_docs/version-3.6/guides/parallel-scraping/modified-detail-route.mjs
  website/versioned_docs/version-3.6/guides/parallel-scraping/parallel-scraper.mjs
  website/versioned_docs/version-3.6/guides/parallel-scraping/parallel-scraping.mdx
  website/versioned_docs/version-3.6/guides/parallel-scraping/shared.mjs
  website/versioned_docs/version-3.7/guides/parallel-scraping/adapted-routes.mjs
  website/versioned_docs/version-3.7/guides/parallel-scraping/modified-detail-route.mjs
  website/versioned_docs/version-3.7/guides/parallel-scraping/parallel-scraper.mjs
  website/versioned_docs/version-3.7/guides/parallel-scraping/parallel-scraping.mdx
  website/versioned_docs/version-3.7/guides/parallel-scraping/shared.mjs
  website/versioned_sidebars/version-3.6-sidebars.json
  website/versioned_sidebars/version-3.7-sidebars.json
Labels: t-tooling

#2277 fix: pass on an invisible CF turnstile
  packages/utils/src/internals/blocked.ts
Labels: t-tooling

#2288 ci: add in option to trigger full redeploy of current images
  .github/workflows/docker-images.yml
  scripts/actions/docker-images/main.ts
Labels: adhoc

#2286 fix: filter out nullish globs
  packages/core/src/enqueue_links/shared.ts
  test/core/enqueue_links/enqueue_links.test.ts
Labels: adhoc

#2293 chore: more debug logs for checking enqueue links strategy
  packages/browser-crawler/src/internals/browser-crawler.ts
  packages/http-crawler/src/internals/http-crawler.ts
Labels: adhoc

#2283 feat: accessing crawler state, key-value store and named datasets via crawling context
  packages/basic-crawler/src/internals/basic-crawler.ts
  packages/core/src/crawlers/crawler_commons.ts
Labels: t-tooling

#2315 feat: Support plain-text sitemap files (sitemap.txt)
  packages/utils/src/internals/sitemap.ts
  packages/utils/test/sitemap.test.ts
Labels: t-tooling
