Repository apify/crawlee, pull requests merged in 2024-05, with the labels that each got.

#2451 docs: fix two typos (array or requests -> array of requests, no much -> not much)
  docs/guides/request_storage.mdx
Labels: adhoc

#2442 fix: sitemap `content-type` check breaks on `content-type` parameters
  packages/utils/package.json
  packages/utils/src/internals/sitemap.ts
  yarn.lock
Labels: bug, adhoc, t-tooling

#2454 fix(core): fire local `SystemInfo` events every second
  packages/core/src/configuration.ts
Labels: adhoc, t-tooling

#2456 perf: optimize adding large amount of requests via `crawler.addRequests()`
  packages/core/src/storages/request_provider.ts
Labels: adhoc, t-tooling

#2459 perf: improve scaling based on memory
  packages/core/src/autoscaling/autoscaled_pool.ts
  packages/core/src/autoscaling/snapshotter.ts
Labels: adhoc, t-tooling

#2390 feat: make `RequestQueue` v2 the default queue, see more on [Apify blog](https://blog.apify.com/new-apify-request-queue/)
  docs/experiments/request_locking.mdx
  packages/basic-crawler/src/internals/basic-crawler.ts
  packages/core/src/storages/index.ts
  packages/core/src/storages/request_provider.ts
  packages/core/src/storages/request_queue.ts
  packages/core/src/storages/request_queue_v2.ts
  test/core/storages/request_queue.test.ts
Labels: t-tooling, tested

#2462 fix: do not drop statistics on migration/resurrection/resume
  packages/basic-crawler/src/internals/basic-crawler.ts
  packages/playwright-crawler/src/internals/adaptive-playwright-crawler.ts
Labels: adhoc, t-tooling

#2468 fix: double tier decrement in tiered proxy
  packages/core/src/proxy_configuration.ts
Labels: adhoc, t-tooling

#2435 feat: add `FileDownload` "crawler"
  packages/http-crawler/src/index.ts
  packages/http-crawler/src/internals/file-download.ts
  test/core/crawlers/file_download.test.ts
Labels: feature, adhoc, t-tooling, tested

#2475 refactor: Remove redundant fields from `StatisticsPersistedState`
  packages/core/src/crawlers/statistics.ts
Labels: adhoc, t-tooling

#2482 fix: provide URLs to the error snapshot
  packages/core/src/crawlers/error_snapshotter.ts
  packages/core/src/crawlers/error_tracker.ts
  packages/core/src/storages/key_value_store.ts
  test/e2e/cheerio-error-snapshot/test.mjs
  test/e2e/puppeteer-error-snapshot/test.mjs
Labels: adhoc, t-tooling, tested

#2481 docs: update keywords
  website/versioned_docs/version-3.10/examples/crawl_sitemap.mdx
  website/versioned_docs/version-3.10/examples/crawler-plugins/index.mdx
  website/versioned_docs/version-3.10/examples/http_crawler.mdx
  website/versioned_docs/version-3.10/examples/http_crawler.ts
  website/versioned_docs/version-3.10/guides/cheerio_crawler.mdx
Labels: t-tooling

#2490 test: Check if the proxy tier drops after an amount of successful requests
  test/core/proxy_configuration.test.ts
Labels: adhoc, t-tooling, tested

#2491 chore: ignore docker state when checking formatting
  biome.json
Labels: adhoc, t-tooling

#2493 chore: run biome as a pre-commit hook
  .husky/pre-commit
  package.json
  yarn.lock
Labels: adhoc, t-tooling

#2492 fix: adjust `URL_NO_COMMAS_REGEX` regexp to allow single character hostnames
  packages/utils/src/internals/general.ts
  test/shared/data/simple_url_list.txt
Labels: adhoc, t-tooling, tested

#2494 fix: investigate and temp fix for possible 0-concurrency bug in RQv2
  biome.json
  packages/core/src/storages/request_provider.ts
  packages/core/src/storages/request_queue.ts
  packages/core/src/storages/request_queue_v2.ts
Labels: adhoc, t-tooling

#2496 feat: Loading sitemaps from string
  packages/utils/src/internals/sitemap.ts
  packages/utils/test/sitemap.test.ts
Labels: t-tooling, tested

#2500 docs: fix homepage gradients
  website/src/components/Gradients.jsx
  website/src/components/Highlights.jsx
  website/static/img/features/gradient.svg
Labels: adhoc, t-tooling

#2497 fix: Autodetect sitemap filetype from content
  packages/utils/package.json
  packages/utils/src/internals/sitemap.ts
  packages/utils/test/sitemap.test.ts
  yarn.lock
Labels: t-tooling, tested

#2505 fix: improve fix for double extension in KVS with HTML files
  packages/memory-storage/src/fs/key-value-store/fs.ts
  packages/memory-storage/test/key-value-store/with-extension.test.ts
Labels: adhoc, t-tooling, tested
