Repository apify/crawlee, pull requests merged in 2024-11, with the labels that each got.

#2734 fix(core): ensure correct column order in CSV export
  packages/core/src/storages/dataset.ts
  test/core/storages/dataset.test.ts
Labels: adhoc, t-tooling, tested

#2737 docs: update docusaurus to v3.6
  package.json
  website/blog/2024/02-22-launching-crawlee-blog/index.md
  website/blog/2024/03-27-how-to-scrape-amazon-using-typescript-cheerio-and-crawlee/index.md
  website/blog/2024/04-23-scrapy-vs-crawlee/index.md
  website/blog/2024/06-10-creating-a-netflix-show-recommender-using-crawlee-and-react/index.md
  website/blog/2024/06-24-proxy-management-in-crawlee/index.md
  website/blog/2024/07-05-launching-crawlee-python/index.md
  website/blog/2024/08-20-problems-in-web-scraping/index.md
  website/blog/2024/08-27-how-to-scrape-infinite-scrolling-pages/index.md
  website/blog/2024/09-12-finding-students-accommodations/index.md
  website/blog/2024/09-30-jsdom-based-scraping/index.md
  website/blog/2024/10-14-linkedin-job-scraper-python/index.md
  website/blog/2024/11-10-web-scraping-tips/index.md
  website/blog/authors.yml
  website/docusaurus.config.js
  website/package.json
  website/patches/@docusaurus+core+3.6.0.patch
  website/src/components/ApiLink.jsx
  website/src/theme/BlogPostItem/Content/index.js
  website/src/theme/BlogPostItem/Footer/index.js
  website/src/theme/BlogPostItem/Header/Authors/index.js
  website/src/theme/BlogPostItem/Header/Info/index.js
  website/src/theme/BlogPostItem/Header/Title/index.js
  website/src/theme/BlogPostItem/index.js
  website/src/theme/BlogPostItems/index.js
  website/src/theme/DocItem/Layout/index.js
  website/src/theme/NavbarItem/ComponentTypes.js
  website/yarn.lock
Labels: adhoc, t-tooling

#2738 docs: switch to the Apify-forked typedoc plugin
  renovate.json
  website/docusaurus.config.js
  website/package.json
  website/src/css/custom.css
  website/yarn.lock
Labels: t-tooling

#2743 feat: `tieredProxyUrls` accept `null` for switching the proxy off
  packages/core/src/proxy_configuration.ts
Labels: t-tooling

#2753 chore: update some dependencies
  package.json
  website/package.json
  website/yarn.lock
  yarn.lock
Labels: adhoc, t-tooling

#2757 docs: fix the Hero section tagline colors
  website/src/pages/index.js
  website/src/pages/index.module.css
Labels: documentation, adhoc, t-tooling
