Repository apify/crawlee, pull requests merged in 2024-02, with the labels that each got.

#2311 feat: add Sitemap.tryCommonNames to check well known sitemap locations
  packages/utils/src/internals/sitemap.ts
  packages/utils/test/sitemap.test.ts
Labels: t-tooling, tested

#2337 fix(puppeteer): support `puppeteer@v22`
  package.json
  packages/browser-pool/src/puppeteer/puppeteer-controller.ts
  packages/browser-pool/src/puppeteer/puppeteer-plugin.ts
  yarn.lock
Labels: adhoc, t-tooling

#2321 fix: `createRequests` works correctly with `exclude` (and nothing else)
  packages/core/src/enqueue_links/shared.ts
  packages/core/test/enqueue_links/user-provided-patterns-with-enqueue-strategy.test.ts
Labels: adhoc, t-tooling, tested

#2338 feat(core): add `userAgent` parameter to `RobotsFile.isAllowed()` + `RobotsFile.from()` helper
  packages/utils/src/internals/robots.ts
  packages/utils/test/robots.test.ts
Labels: adhoc, t-tooling, tested

#2340 docs: introduction rewrites
  docs/introduction/01-setting-up.mdx
  docs/introduction/02-first-crawler.mdx
  docs/introduction/03-adding-urls.mdx
  docs/introduction/04-real-world-project.mdx
  docs/introduction/05-crawling.mdx
  docs/introduction/06-scraping.mdx
  docs/introduction/07-saving-data.mdx
  docs/introduction/08-refactoring.mdx
  docs/introduction/09-deployment.mdx
  docs/introduction/index.mdx
Labels: t-docs

#2339 feat: `KeyValueStore.recordExists()`
  packages/core/src/storages/key_value_store.ts
  packages/memory-storage/src/resource-clients/key-value-store.ts
  packages/types/src/storages.ts
  test/core/storages/key_value_store.test.ts
Labels: adhoc, t-tooling, tested

#2346 test: do not import puppeteer directly from inside browser pool
  packages/browser-pool/src/puppeteer/puppeteer-controller.ts
  packages/browser-pool/src/puppeteer/puppeteer-plugin.ts
Labels: adhoc, t-tooling

#2347 chore: remove unused poolPromise property on AutoscaledPool
  packages/core/src/autoscaling/autoscaled_pool.ts
Labels: adhoc, t-tooling

#2316 feat: adaptive playwright crawler
  package.json
  packages/basic-crawler/src/internals/basic-crawler.ts
  packages/browser-crawler/package.json
  packages/browser-crawler/src/internals/browser-crawler.ts
  packages/core/src/crawlers/crawler_commons.ts
  packages/core/src/crawlers/statistics.ts
  packages/core/src/enqueue_links/enqueue_links.ts
  packages/core/src/enqueue_links/shared.ts
  packages/playwright-crawler/package.json
  packages/playwright-crawler/src/index.ts
  packages/playwright-crawler/src/internals/adaptive-playwright-crawler.ts
  packages/playwright-crawler/src/internals/utils/playwright-utils.ts
  packages/playwright-crawler/src/internals/utils/rendering-type-prediction.ts
  packages/playwright-crawler/src/logistic-regression.d.ts
  test/core/crawlers/adaptive_playwright_crawler.test.ts
  test/shared/MemoryStorageEmulator.ts
  yarn.lock
Labels: adhoc, t-tooling, tested

#2354 docs: add blog
  website/blog/2024-02-22-launching-crawlee-blog.md
  website/docusaurus.config.js
Labels: adhoc, t-tooling

#2355 fix: fix crawling context type in `router.addHandler()`
  packages/core/src/crawlers/crawler_commons.ts
  test/core/router.test.ts
Labels: adhoc, t-tooling, tested

#2356 chore: bump to puppeteer v22.2
  package.json
  yarn.lock
Labels: adhoc, t-tooling

#2359 chore: run docker ci hourly
  .github/workflows/docker-images.yml
Labels: adhoc, t-tooling

#2372 fix: use 0 (number) instead of false as default for sessionRotationCount
  packages/core/src/request.ts
Labels: adhoc, t-tooling
