Repository apify/crawlee, pull requests merged in 2024-04, with the labels that each got.

#2399 fix(puppeteer): allow passing `networkidle` to `waitUntil` in `gotoExtended`
  packages/puppeteer-crawler/src/internals/utils/puppeteer_utils.ts
  test/core/puppeteer_utils.test.ts
Labels: t-tooling, tested

#2400 fix: notify autoscaled pool about newly added requests
  packages/basic-crawler/src/internals/basic-crawler.ts
  packages/core/src/autoscaling/autoscaled_pool.ts
Labels: adhoc, t-tooling

#2392 feat: better `newUrlFunction` for ProxyConfiguration
  packages/browser-crawler/src/internals/browser-crawler.ts
  packages/browser-pool/src/abstract-classes/browser-controller.ts
  packages/browser-pool/src/browser-pool.ts
  packages/core/src/proxy_configuration.ts
  test/core/proxy_configuration.test.ts
Labels: t-tooling, tested

#2396 feat: expand #shadow-root elements automatically in `parseWithCheerio` helper
  packages/browser-crawler/src/internals/browser-crawler.ts
  packages/playwright-crawler/src/internals/playwright-crawler.ts
  packages/playwright-crawler/src/internals/utils/playwright-utils.ts
  packages/puppeteer-crawler/src/internals/puppeteer-crawler.ts
  packages/puppeteer-crawler/src/internals/utils/puppeteer_utils.ts
  packages/utils/src/internals/general.ts
  test/core/playwright_utils.test.ts
  test/core/puppeteer_utils.test.ts
Labels: adhoc, t-tooling, tested

#2402 test: fix e2e tests after yet another store redesign
  test/e2e/playwright-enqueue-links/actor/main.js
  test/e2e/playwright-enqueue-links/test.mjs
Labels: adhoc, t-tooling, tested

#2408 fix: sitemaps support `application/xml`
  packages/utils/src/internals/robots.ts
  packages/utils/src/internals/sitemap.ts
Labels: adhoc, t-tooling

#2411 fix: include actual key in error message of KVS' `setValue`
  packages/core/src/storages/key_value_store.ts
  test/core/storages/key_value_store.test.ts
Labels: t-platform, tested

#2415 feat: `createAdaptivePlaywrightRouter` utility
  packages/core/src/router.ts
  packages/playwright-crawler/src/internals/adaptive-playwright-crawler.ts
Labels: t-tooling

#2422 fix: break up growing stack in `AutoscaledPool.notify`
  packages/core/src/autoscaling/autoscaled_pool.ts
Labels: t-tooling

#2429 chore: update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: adhoc, t-tooling

#2433 docs: mitigate logotype "aliasing" on homepage
  website/src/pages/index.module.css
Labels: adhoc, t-tooling

#2438 ci: test on node 22
  .github/workflows/release.yml
  .github/workflows/test-ci.yml
Labels: adhoc, t-tooling
