Repository apify/crawlee, pull requests merged in 2024-09, with the labels that each got.

#2651 docs: add intercom messenger
  website/docusaurus.config.js
Labels: t-web

#2656 fix(RequestQueueV2): reset recently handled cache too if the queue is pending for too long
  packages/core/src/storages/request_provider.ts
Labels: adhoc, t-tooling

#2657 ci: fix turbo and yarn incompatibility with node 16
  .github/workflows/test-ci.yml
Labels: adhoc, t-tooling

#2667 docs: changes regarding the updated structure of py templates
  website/blog/2024/07-05-launching-crawlee-python/index.md
  website/blog/2024/08-27-how-to-scrape-infinite-scrolling-pages/index.md
Labels: t-tooling

#2673 fix: `SitemapRequestList.teardown()` doesn't break `persistState` calls
  packages/core/src/storages/sitemap_request_list.ts
  packages/utils/src/internals/general.ts
  test/core/sitemap_request_list.test.ts
Labels: t-tooling, tested

#2665 docs: new blog and minor changes
  website/blog/2024/07-05-launching-crawlee-python/index.md
  website/blog/2024/08-27-how-to-scrape-infinite-scrolling-pages/index.md
  website/blog/2024/09-12-finding-students-accommodations/img/PEP.webp
  website/blog/2024/09-12-finding-students-accommodations/img/dynamic-websites.webp
  website/blog/2024/09-12-finding-students-accommodations/img/final-results.webp
  website/blog/2024/09-12-finding-students-accommodations/img/javascript.webp
  website/blog/2024/09-12-finding-students-accommodations/img/json.webp
  website/blog/2024/09-12-finding-students-accommodations/img/listing.webp
  website/blog/2024/09-12-finding-students-accommodations/img/request.webp
  website/blog/2024/09-12-finding-students-accommodations/img/result.webp
  website/blog/2024/09-12-finding-students-accommodations/img/server.webp
  website/blog/2024/09-12-finding-students-accommodations/index.md
Labels: t-tooling

#2675 chore: update dependencies
  package.json
  packages/browser-pool/src/playwright/playwright-browser.ts
  packages/browser-pool/src/playwright/playwright-plugin.ts
  packages/core/src/storages/sitemap_request_list.ts
  packages/puppeteer-crawler/src/internals/puppeteer-crawler.ts
  test/browser-pool/browser-plugins/plugins.test.ts
  test/core/crawlers/puppeteer_crawler.test.ts
  website/package.json
  website/yarn.lock
  yarn.lock
Labels: adhoc, t-tooling, tested

#2684 fix(puppeteer): rename `ignoreHTTPSErrors` to `acceptInsecureCerts` to support v23
  packages/browser-crawler/src/internals/browser-crawler.ts
  test/e2e/puppeteer-ignore-ssl-errors/actor/main.js
  test/e2e/puppeteer-throw-on-ssl-errors/actor/main.js
Labels: adhoc, t-tooling, tested

#2683 fix(core): trigger `errorHandler` for session errors
  packages/basic-crawler/src/internals/basic-crawler.ts
  test/core/crawlers/basic_crawler.test.ts
Labels: adhoc, t-tooling, tested

#2682 fix(core): accept `UInt8Array` in `KVS.setValue()`
  packages/core/src/request.ts
  packages/core/src/serialization.ts
  packages/core/src/storages/key_value_store.ts
  packages/playwright-crawler/src/internals/utils/playwright-utils.ts
  packages/puppeteer-crawler/src/internals/utils/puppeteer_utils.ts
Labels: adhoc, t-tooling

#2685 chore: update more dependencies
  package.json
  packages/basic-crawler/src/internals/basic-crawler.ts
  packages/browser-pool/src/fingerprinting/hooks.ts
  packages/core/package.json
  packages/core/src/cookie_utils.ts
  packages/core/src/session_pool/session.ts
  packages/core/src/storages/utils.ts
  packages/memory-storage/src/resource-clients/dataset.ts
  packages/memory-storage/src/resource-clients/key-value-store.ts
  packages/memory-storage/src/resource-clients/request-queue.ts
  test/core/crawlers/puppeteer_crawler.test.ts
  yarn.lock
Labels: adhoc, t-tooling, tested
