Repository apify/crawlee, pull requests merged in 2024-08, with the labels that each got.

#2603 chore: try to reduce fs calls for listing heads
  packages/memory-storage/src/fs/request-queue/fs.ts
  packages/memory-storage/src/fs/request-queue/index.ts
  packages/memory-storage/src/fs/request-queue/memory.ts
  packages/memory-storage/src/resource-clients/request-queue.ts
Labels: adhoc, t-tooling

#2623 fix: Use the correct mutex in memory storage RequestQueueClient
  packages/memory-storage/src/resource-clients/request-queue.ts
Labels: adhoc, t-tooling

#2619 feat: resilient sitemap loading
  packages/core/src/storages/sitemap_request_list.ts
  packages/utils/src/internals/sitemap.ts
  test/core/sitemap_request_list.test.ts
Labels: feature, t-tooling, tested

#2625 docs: add blog
  website/blog/2024/08-20-problems-in-web-scraping/img/problems-in-scraping.webp
  website/blog/2024/08-20-problems-in-web-scraping/index.md
Labels: t-tooling

#2631 feat: `globs` & `regexps` for `SitemapRequestList`
  packages/core/src/storages/sitemap_request_list.ts
  test/core/sitemap_request_list.test.ts
Labels: adhoc, t-tooling, tested

#2641 fix: use namespace imports for cheerio to be compatible with v1
  packages/utils/src/internals/cheerio.ts
  packages/utils/src/internals/social.ts
  test/utils/cheerio.test.ts
Labels: adhoc, t-tooling, tested

#2642 chore: update dev dependencies
  .github/workflows/docker-images.yml
  .github/workflows/release.yml
  .github/workflows/test-ci.yml
  .github/workflows/test-e2e.yml
  .github/workflows/update_new_issue.yml
  package.json
  turbo.json
  website/package.json
  yarn.lock
Labels: adhoc, t-tooling

#2644 chore: update playwright to 1.46
  package.json
  test/core/crawlers/playwright_crawler.test.ts
  yarn.lock
Labels: adhoc, t-tooling, tested
