Repository apify/crawlee, pull requests merged in 2024-10, with the labels that each got.

#2690 fix: `prolong-` and `deleteRequestLock` `forefront` option
  packages/memory-storage/src/resource-clients/request-queue.ts
  packages/memory-storage/test/request-queue/forefront.test.ts
Labels: adhoc, t-tooling, tested

#2694 test: fix puppeteer e2e tests
  .github/workflows/test-e2e.yml
  test/e2e/proxy-rotation/actor/Dockerfile
  test/e2e/puppeteer-default/actor/Dockerfile
  test/e2e/puppeteer-enqueue-links/actor/Dockerfile
  test/e2e/puppeteer-error-snapshot/actor/Dockerfile
  test/e2e/puppeteer-ignore-ssl-errors/actor/Dockerfile
  test/e2e/puppeteer-initial-cookies/actor/Dockerfile
  test/e2e/puppeteer-page-info/actor/Dockerfile
  test/e2e/puppeteer-store-pagination-jquery/actor/Dockerfile
  test/e2e/puppeteer-store-pagination/actor/Dockerfile
  test/e2e/puppeteer-throw-on-ssl-errors/actor/Dockerfile
Labels: adhoc, t-tooling, tested

#2689 fix: `forefront` request fetching in RQv2
  packages/core/src/storages/request_provider.ts
  packages/core/src/storages/request_queue_v2.ts
  test/core/storages/request_queue.test.ts
Labels: t-tooling, tested

#2695 fix: check `.isFinished()` before `RequestList` reads
  packages/basic-crawler/src/internals/basic-crawler.ts
Labels: adhoc, t-tooling

#2696 fix: decode special characters in proxy `username` and `password`
  packages/core/src/proxy_configuration.ts
  test/core/proxy_configuration.test.ts
Labels: adhoc, t-tooling, tested

#2687 docs: add Jsdom approach blog
  website/blog/2024/09-12-finding-students-accommodations/index.md
  website/blog/2024/09-30-jsdom-based-scraping/img/code-flow.webp
  website/blog/2024/09-30-jsdom-based-scraping/img/jsdom.webp
  website/blog/2024/09-30-jsdom-based-scraping/img/tiktok-trends.webp
  website/blog/2024/09-30-jsdom-based-scraping/index.md
Labels: t-tooling

#2705 fix: update `fingerprintGeneratorOptions` types
  packages/browser-pool/src/fingerprinting/types.ts
Labels: t-tooling

#2709 fix: `.trim()` urls from pretty-printed sitemap.xml files
  packages/utils/src/internals/sitemap.ts
  packages/utils/test/sitemap.test.ts
Labels: t-tooling, tested

#2661 feat: allow using other HTTP clients
  docs/guides/custom-http-client/custom-http-client.mdx
  docs/guides/custom-http-client/implementation.ts
  docs/guides/custom-http-client/usage.ts
  package.json
  packages/basic-crawler/src/internals/basic-crawler.ts
  packages/basic-crawler/src/internals/send-request.ts
  packages/browser-pool/src/fingerprinting/hooks.ts
  packages/core/src/cookie_utils.ts
  packages/core/src/http_clients/base-http-client.ts
  packages/core/src/http_clients/form-data-like.ts
  packages/core/src/http_clients/got-scraping-http-client.ts
  packages/core/src/http_clients/index.ts
  packages/core/src/index.ts
  packages/core/src/session_pool/session.ts
  packages/http-crawler/src/internals/file-download.ts
  packages/http-crawler/src/internals/http-crawler.ts
  packages/utils/src/index.ts
  packages/utils/src/internals/url.ts
  test/core/crawlers/http_crawler.test.ts
  test/e2e/cheerio-curl-impersonate-ts/actor/.actor/actor.json
  test/e2e/cheerio-curl-impersonate-ts/actor/.eslintrc.json
  test/e2e/cheerio-curl-impersonate-ts/actor/.gitignore
  test/e2e/cheerio-curl-impersonate-ts/actor/Dockerfile
  test/e2e/cheerio-curl-impersonate-ts/actor/main.ts
  test/e2e/cheerio-curl-impersonate-ts/actor/package.json
  test/e2e/cheerio-curl-impersonate-ts/actor/tsconfig.json
  test/e2e/cheerio-curl-impersonate-ts/test.mjs
  test/e2e/tools.mjs
  website/sidebars.js
  yarn.lock
Labels: product roadmap, t-tooling, tested
