Repository apify/crawlee, pull requests merged in 2024-03, with the labels that each got.

#2373 chore: fix internal attribute naming in SystemStatus
  packages/core/src/autoscaling/system_status.ts
  test/core/autoscaling/system_status.test.ts
Labels: adhoc, t-tooling, tested

#2376 fix(core): solve possible dead locks in `RequestQueueV2`
  docs/experiments/request_locking.mdx
  packages/core/src/storages/request_provider.ts
  packages/core/src/storages/request_queue.ts
  packages/core/src/storages/request_queue_v2.ts
  website/versioned_docs/version-3.5/experiments/request_locking.mdx
  website/versioned_docs/version-3.6/experiments/request_locking.mdx
  website/versioned_docs/version-3.7/experiments/request_locking.mdx
  website/versioned_docs/version-3.8/experiments/request_locking.mdx
Labels: bug, adhoc, t-tooling

#2391 chore: update dependencies except playwright
  package.json
  website/package.json
  website/yarn.lock
  yarn.lock
Labels: adhoc, t-tooling

#2348 feat: `tieredProxyUrls` for ProxyConfiguration
  packages/basic-crawler/src/internals/basic-crawler.ts
  packages/browser-crawler/src/internals/browser-crawler.ts
  packages/browser-pool/src/abstract-classes/browser-controller.ts
  packages/browser-pool/src/abstract-classes/browser-plugin.ts
  packages/browser-pool/src/browser-pool.ts
  packages/browser-pool/src/launch-context.ts
  packages/core/src/proxy_configuration.ts
  packages/http-crawler/src/internals/http-crawler.ts
  test/core/crawlers/basic_crawler.test.ts
  test/core/crawlers/cheerio_crawler.test.ts
  test/core/proxy_configuration.test.ts
Labels: adhoc, t-tooling, tested

#2394 test: circumvent ORB in `blockRequests` tests
  test/core/playwright_utils.test.ts
Labels: adhoc, t-tooling, tested
