Repository apify/crawlee, pull requests merged in 2024-06, with the labels that each got.

#2517 docs: wait before scrolling fragments into viewport
  website/package.json
  website/patches/@docusaurus+core+3.4.0.patch
  website/yarn.lock
Labels: bug, documentation, t-tooling

#2518 fix: respect implicit router when no `requestHandler` is provided in `AdaptiveCrawler`
  .eslintrc.json
  packages/core/src/crawlers/crawler_commons.ts
  packages/core/src/typedefs.ts
  packages/playwright-crawler/src/internals/adaptive-playwright-crawler.ts
  packages/utils/src/internals/typedefs.ts
Labels: adhoc, t-tooling

#2522 feat: add `waitForSelector` context helper + `parseWithCheerio` in adaptive crawler
  biome.json
  packages/cheerio-crawler/src/internals/cheerio-crawler.ts
  packages/core/src/crawlers/crawler_commons.ts
  packages/http-crawler/src/internals/http-crawler.ts
  packages/jsdom-crawler/src/internals/jsdom-crawler.ts
  packages/linkedom-crawler/src/internals/linkedom-crawler.ts
  packages/playwright-crawler/src/internals/adaptive-playwright-crawler.ts
  packages/playwright-crawler/src/internals/utils/playwright-utils.ts
  packages/puppeteer-crawler/src/internals/utils/puppeteer_utils.ts
  scripts/typescript_fixes.mjs
  test/core/crawlers/adaptive_playwright_crawler.test.ts
  test/core/crawlers/http_crawler.test.ts
  test/e2e/playwright-enqueue-links-base/actor/main.js
Labels: adhoc, t-tooling, tested

#2524 fix(adaptive-crawler): log only once for the committed request handler execution
  packages/playwright-crawler/src/internals/adaptive-playwright-crawler.ts
Labels: adhoc, t-tooling

#2526 fix: make `crawler.log` publicly accessible
  packages/basic-crawler/src/internals/basic-crawler.ts
  packages/http-crawler/src/internals/http-crawler.ts
Labels: adhoc, t-tooling

#2527 docs: proxy tier logging
  packages/core/src/proxy_configuration.ts
Labels: adhoc, t-tooling

#2530 fix: fix detection of HTTP site when using the `useState` in adaptive crawler
  packages/playwright-crawler/src/internals/adaptive-playwright-crawler.ts
Labels: adhoc, t-tooling

#2531 fix: mark `context.request.loadedUrl` and `id` as required inside the request handler
  packages/basic-crawler/src/internals/basic-crawler.ts
  packages/browser-crawler/src/internals/browser-crawler.ts
  packages/core/src/crawlers/crawler_commons.ts
  packages/core/src/router.ts
  packages/http-crawler/src/internals/http-crawler.ts
  packages/playwright-crawler/src/internals/adaptive-playwright-crawler.ts
  packages/playwright-crawler/src/internals/playwright-crawler.ts
  test/core/crawlers/cheerio_crawler.test.ts
Labels: adhoc, t-tooling, tested

#2542 feat: add `iframe` expansion to `parseWithCheerio` in browsers
  packages/browser-crawler/src/internals/browser-crawler.ts
  packages/playwright-crawler/src/internals/utils/playwright-utils.ts
  packages/puppeteer-crawler/src/internals/utils/puppeteer_utils.ts
  test/core/playwright_utils.test.ts
  test/core/puppeteer_utils.test.ts
  test/shared/_helper.ts
Labels: t-tooling, tested

#2546 docs: file download examples
  docs/examples/file_download.mdx
  docs/examples/file_download.ts
  docs/examples/file_download_stream.mdx
  docs/examples/file_download_stream.ts
  packages/http-crawler/src/internals/file-download.ts
Labels: adhoc, t-tooling

#2554 docs: compress blog pictures (webp)
  website/blog/2024/02-22-launching-crawlee-blog/index.md
  website/blog/2024/03-27-how-to-scrape-amazon-using-typescript-cheerio-and-crawlee/img/dev-tools-example.png
  website/blog/2024/03-27-how-to-scrape-amazon-using-typescript-cheerio-and-crawlee/img/dev-tools-example.webp
  website/blog/2024/03-27-how-to-scrape-amazon-using-typescript-cheerio-and-crawlee/img/fields-to-scrape.png
  website/blog/2024/03-27-how-to-scrape-amazon-using-typescript-cheerio-and-crawlee/img/fields-to-scrape.webp
  website/blog/2024/03-27-how-to-scrape-amazon-using-typescript-cheerio-and-crawlee/img/how-to-scrape-amazon.png
  website/blog/2024/03-27-how-to-scrape-amazon-using-typescript-cheerio-and-crawlee/img/how-to-scrape-amazon.webp
  website/blog/2024/03-27-how-to-scrape-amazon-using-typescript-cheerio-and-crawlee/img/lukasp.png
  website/blog/2024/03-27-how-to-scrape-amazon-using-typescript-cheerio-and-crawlee/img/lukasp.webp
  website/blog/2024/03-27-how-to-scrape-amazon-using-typescript-cheerio-and-crawlee/index.md
  website/blog/2024/04-23-scrapy-vs-crawlee/img/scrapy-vs-crawlee.png
  website/blog/2024/04-23-scrapy-vs-crawlee/img/scrapy-vs-crawlee.webp
  website/blog/2024/04-23-scrapy-vs-crawlee/index.md
  website/blog/2024/06-10-creating-a-netflix-show-recommender-using-crawlee-and-react/img/create-netflix-show-recommender.png
  website/blog/2024/06-10-creating-a-netflix-show-recommender-using-crawlee-and-react/img/create-netflix-show-recommender.webp
  website/blog/2024/06-10-creating-a-netflix-show-recommender-using-crawlee-and-react/img/genre.png
  website/blog/2024/06-10-creating-a-netflix-show-recommender-using-crawlee-and-react/img/genre.webp
  website/blog/2024/06-10-creating-a-netflix-show-recommender-using-crawlee-and-react/img/react.png
  website/blog/2024/06-10-creating-a-netflix-show-recommender-using-crawlee-and-react/img/react.webp
  website/blog/2024/06-10-creating-a-netflix-show-recommender-using-crawlee-and-react/img/title.png
  website/blog/2024/06-10-creating-a-netflix-show-recommender-using-crawlee-and-react/img/title.webp
  website/blog/2024/06-10-creating-a-netflix-show-recommender-using-crawlee-and-react/img/viteandreact.png
  website/blog/2024/06-10-creating-a-netflix-show-recommender-using-crawlee-and-react/img/viteandreact.webp
  website/blog/2024/06-10-creating-a-netflix-show-recommender-using-crawlee-and-react/index.md
Labels: adhoc, t-tooling
