Repository apify/crawlee, pull requests merged in 2025-05, with the labels that each got.

#2946 chore(ci): fix e2e tests
  test/e2e/cheerio-default-ts/actor/tsconfig.json
  test/e2e/cheerio-impit-ts/actor/tsconfig.json
  test/e2e/cheerio-stop-resume-ts/actor/tsconfig.json
  test/e2e/jsdom-default-ts/actor/tsconfig.json
  test/e2e/jsdom-react-ts/actor/tsconfig.json
  test/e2e/linkedom-default-ts/actor/tsconfig.json
Labels: adhoc, t-tooling, tested

#2961 fix(core): respect `systemInfoV2` in snapshotter
  packages/core/src/autoscaling/snapshotter.ts
  packages/core/src/events/local_event_manager.ts
Labels: adhoc, t-tooling

#2960 feat: Add Segment analytics [internal]
  .github/workflows/docs.yml
  .github/workflows/test-ci.yml
  website/docusaurus.config.js
  website/src/plugins/docusaurus-plugin-segment/index.js
  website/src/plugins/docusaurus-plugin-segment/segment.js
Labels: t-web

#2954 feat(impit-client): bump `impit` version to v0.4
  packages/impit-client/package.json
  packages/impit-client/src/index.ts
  yarn.lock
Labels: adhoc, t-tooling

#2963 fix: Optimize request unlocking to get rid of unnecessary unlock calls
  packages/basic-crawler/src/internals/basic-crawler.ts
  packages/core/src/storages/request_queue_v2.ts
Labels: adhoc, t-tooling

#2965 docs: fix changelog
  CHANGELOG.md
Labels: t-tooling

#2967 chore: use self-hosted httpbin instance in e2e tests
  .github/workflows/test-e2e.yml
  test/e2e/cheerio-curl-impersonate-ts/actor/main.ts
  test/e2e/cheerio-impit-ts/actor/main.ts
Labels: adhoc, t-tooling, tested

#2973 docs: Remove a duplicated analytics page view
  website/src/plugins/docusaurus-plugin-segment/index.js
  website/src/plugins/docusaurus-plugin-segment/segment.js
Labels: adhoc, t-web

#2975 feat: Allow the AdaptivePlaywrightCrawler result comparator to signal an inconclusive result
  packages/playwright-crawler/src/internals/adaptive-playwright-crawler.ts
Labels: adhoc, t-tooling
