Repository apify/crawlee, pull requests merged in 2025-04, with the labels that each got.

#2905 chore(e2e): fix tests after the documentation redesign
  test/e2e/cheerio-default-ts/actor/main.ts
  test/e2e/cheerio-default/actor/main.js
  test/e2e/cheerio-max-requests/actor/main.js
  test/e2e/cheerio-page-info/actor/main.js
  test/e2e/cheerio-request-queue-v2/actor/main.js
  test/e2e/cheerio-stop-resume-ts/actor/main.ts
  test/e2e/jsdom-default-ts/actor/main.ts
  test/e2e/linkedom-default-ts/actor/main.ts
  test/e2e/playwright-default/actor/main.js
  test/e2e/playwright-multi-run/actor/main.js
  test/e2e/puppeteer-default/actor/main.js
Labels: adhoc, t-tooling, tested

#2907 fix: treat `406` as other `4xx` status codes in `HttpCrawler`
  packages/http-crawler/src/internals/http-crawler.ts
  test/core/crawlers/cheerio_crawler.test.ts
Labels: t-tooling, tested

#2910 feat: add `respectRobotsTxtFile` crawler option
  packages/basic-crawler/src/internals/basic-crawler.ts
  packages/browser-crawler/src/internals/browser-crawler.ts
  packages/cheerio-crawler/src/internals/cheerio-crawler.ts
  packages/core/src/enqueue_links/enqueue_links.ts
  packages/http-crawler/src/internals/http-crawler.ts
  packages/jsdom-crawler/src/internals/jsdom-crawler.ts
  packages/linkedom-crawler/src/internals/linkedom-crawler.ts
  packages/utils/src/internals/robots.ts
  test/e2e/cheerio-robots-file/actor/.actor/actor.json
  test/e2e/cheerio-robots-file/actor/.gitignore
  test/e2e/cheerio-robots-file/actor/Dockerfile
  test/e2e/cheerio-robots-file/actor/main.js
  test/e2e/cheerio-robots-file/actor/package.json
  test/e2e/cheerio-robots-file/test.mjs
  test/e2e/playwright-robots-file/actor/.actor/actor.json
  test/e2e/playwright-robots-file/actor/.gitignore
  test/e2e/playwright-robots-file/actor/Dockerfile
  test/e2e/playwright-robots-file/actor/main.js
  test/e2e/playwright-robots-file/actor/package.json
  test/e2e/playwright-robots-file/test.mjs
Labels: adhoc, t-tooling, tested

#2913 fix: rename `RobotsFile` to `RobotsTxtFile`
  packages/basic-crawler/src/internals/basic-crawler.ts
  packages/browser-crawler/src/internals/browser-crawler.ts
  packages/cheerio-crawler/src/internals/cheerio-crawler.ts
  packages/core/src/enqueue_links/enqueue_links.ts
  packages/jsdom-crawler/src/internals/jsdom-crawler.ts
  packages/linkedom-crawler/src/internals/linkedom-crawler.ts
  packages/utils/src/internals/robots.ts
  packages/utils/src/internals/sitemap.ts
  packages/utils/test/robots.test.ts
Labels: adhoc, t-tooling, tested

#2916 feat: add `onSkippedRequest` option
  packages/basic-crawler/src/internals/basic-crawler.ts
  packages/browser-crawler/src/internals/browser-crawler.ts
  packages/cheerio-crawler/src/internals/cheerio-crawler.ts
  packages/core/src/enqueue_links/enqueue_links.ts
  packages/jsdom-crawler/src/internals/jsdom-crawler.ts
  packages/linkedom-crawler/src/internals/linkedom-crawler.ts
  test/e2e/adaptive-playwright-robots-file/actor/.actor/actor.json
  test/e2e/adaptive-playwright-robots-file/actor/.gitignore
  test/e2e/adaptive-playwright-robots-file/actor/Dockerfile
  test/e2e/adaptive-playwright-robots-file/actor/main.js
  test/e2e/adaptive-playwright-robots-file/actor/package.json
  test/e2e/adaptive-playwright-robots-file/test.mjs
  test/e2e/tools.mjs
Labels: adhoc, t-tooling, tested

#2921 fix: Fix trailing slash removal in BrowserPool
  packages/browser-pool/src/anonymize-proxy.ts
  packages/browser-pool/test/tsconfig.json
  test/browser-pool/anonymize-proxy-sugar.test.ts
Labels: t-tooling, tested

#2923 fix: Persist SitemapRequestList state periodically
  packages/core/src/storages/sitemap_request_list.ts
Labels: t-tooling

#2924 chore(hotfix): Fix SitemapRequestList persist state event binding
  packages/core/src/storages/sitemap_request_list.ts
Labels: adhoc, t-tooling

#2926 chore(hotfix): Fix SitemapRequestList persist state event binding, vol. 2
  packages/core/src/storages/sitemap_request_list.ts
Labels: adhoc, t-tooling

#2927 docs: fix missing sidebar in web server guide
  docs/guides/running-in-web-server/running-in-web-server.mdx
  website/sidebars.js
  website/versioned_docs/version-3.11/guides/running-in-web-server/running-in-web-server.mdx
  website/versioned_docs/version-3.12/guides/running-in-web-server/running-in-web-server.mdx
  website/versioned_docs/version-3.13/guides/running-in-web-server/running-in-web-server.mdx
  website/versioned_sidebars/version-3.11-sidebars.json
  website/versioned_sidebars/version-3.12-sidebars.json
  website/versioned_sidebars/version-3.13-sidebars.json
Labels: adhoc, t-tooling

#2912 refactor: Minor adjustments to AdaptivePlaywrightCrawler
  packages/core/src/crawlers/crawler_commons.ts
  packages/playwright-crawler/src/index.ts
  packages/playwright-crawler/src/internals/adaptive-playwright-crawler.ts
  packages/playwright-crawler/src/internals/utils/rendering-type-prediction.ts
  test/core/crawlers/adaptive_playwright_crawler.test.ts
Labels: t-tooling, tested

#2928 fix: disable default fingerprints in the Camoufox template
  docs/guides/avoid_blocking_camoufox.ts
  packages/templates/templates/camoufox-ts/src/main.ts
Labels: adhoc, t-tooling

#2930 feat: pass `response` to `FileDownload.streamHandler`
  packages/http-crawler/src/internals/file-download.ts
  test/core/crawlers/file_download.test.ts
Labels: adhoc, t-tooling, tested

#2935 chore: disallow yarn updates, allow docusaurus updates
  renovate.json
Labels: t-tooling

#2934 docs: small ui fixes and new og images
  website/docusaurus.config.js
  website/src/components/Homepage/LanguageInfoWidget.module.css
  website/src/pages/index.js
  website/src/theme/Navbar/Logo/index.module.css
  website/static/img/crawlee-js-og.png
  website/static/img/crawlee-og.png
Labels: t-web

#2948 fix: respect `autoscaledPoolOptions.isTaskReadyFunction` option
  packages/basic-crawler/src/internals/basic-crawler.ts
  test/core/crawlers/basic_crawler.test.ts
Labels: adhoc, t-tooling, tested

#2949 fix: convert `@apilink` to `@link` on build
  scripts/typescript_fixes.mjs
Labels: adhoc, t-tooling

#2950 fix: await `_createPageForBrowser` in browser pool
  packages/browser-pool/src/browser-pool.ts
Labels: adhoc, t-tooling

#2941 fix: Fix useState behavior in adaptive crawler
  packages/core/src/crawlers/crawler_commons.ts
  packages/playwright-crawler/src/internals/adaptive-playwright-crawler.ts
  test/core/crawlers/adaptive_playwright_crawler.test.ts
Labels: adhoc, t-tooling, tested
