Repository apify/crawlee, pull requests merged in 2025-06, with the labels that each got.

#2991 fix: enable full cookie support for `ImpitHttpClient`
  packages/http-crawler/src/internals/http-crawler.ts
  packages/impit-client/package.json
  packages/impit-client/src/index.ts
  test/core/crawlers/http_crawler.test.ts
  yarn.lock
Labels: adhoc, t-tooling, tested

#2987 fix: Persist rendering type detection results in `AdaptivePlaywrightCrawler`
  packages/core/src/index.ts
  packages/core/src/recoverable_state.ts
  packages/core/tsconfig.build.json
  packages/playwright-crawler/src/internals/adaptive-playwright-crawler.ts
  packages/playwright-crawler/src/internals/utils/rendering-type-prediction.ts
  packages/playwright-crawler/src/logistic-regression.d.ts
  packages/utils/tsconfig.build.json
  test/core/crawlers/adaptive_playwright_crawler.test.ts
  test/core/recoverable_state.test.ts
Labels: t-tooling, tested

#3011 refactor: Fix rendering type detection persistence
  packages/playwright-crawler/src/internals/utils/rendering-type-prediction.ts
  test/core/crawlers/adaptive_playwright_crawler.test.ts
Labels: adhoc, t-tooling, tested

#3012 test: Update fix-playwright-multi-run e2e test
  test/e2e/playwright-multi-run/actor/main.js
  test/e2e/playwright-multi-run/test.mjs
Labels: adhoc, t-tooling, tested

#3013 feat: Accept (Async)Iterables in `addRequests` methods
  packages/basic-crawler/src/internals/basic-crawler.ts
  packages/core/src/storages/request_provider.ts
  packages/core/src/storages/request_queue_v2.ts
  packages/utils/src/index.ts
  packages/utils/src/internals/iterables.ts
  test/core/crawlers/basic_crawler.test.ts
  test/core/enqueue_links/click_elements.test.ts
  test/core/enqueue_links/enqueue_links.test.ts
  test/utils/iterables.test.ts
Labels: t-tooling, tested

#3021 fix: Fix link filtering in enqueueLinks in AdaptivePlaywrightCrawler
  packages/core/src/crawlers/crawler_commons.ts
  packages/core/src/enqueue_links/enqueue_links.ts
  packages/playwright-crawler/src/internals/adaptive-playwright-crawler.ts
  test/core/crawlers/adaptive_playwright_crawler.test.ts
Labels: t-tooling, tested

#3028 chore: bump fingerprinting tools and `impit` to latest versions
  packages/browser-pool/package.json
  packages/impit-client/package.json
  yarn.lock
Labels: adhoc, t-tooling

#3026 feat: Report links skipped because of various filter conditions
  packages/basic-crawler/src/internals/basic-crawler.ts
  packages/browser-crawler/src/internals/browser-crawler.ts
  packages/core/src/enqueue_links/enqueue_links.ts
  packages/core/src/enqueue_links/shared.ts
  packages/http-crawler/src/internals/http-crawler.ts
  packages/playwright-crawler/src/internals/adaptive-playwright-crawler.ts
Labels: t-tooling
