Repository apify/crawlee, pull requests merged in 2025-02, with the labels that each got.

#2831 feat: remove old docker CI
  .github/workflows/docker-images.yml
  .github/workflows/release.yml
  .github/workflows/test-ci.yml
  scripts/actions/docker-images/api.ts
  scripts/actions/docker-images/bun.lockb
  scripts/actions/docker-images/main.ts
  scripts/actions/docker-images/package.json
  scripts/actions/docker-images/state.json
Labels: adhoc, t-tooling

#2839 test: skip flaky e2e test
  test/e2e/playwright-enqueue-links-base/test.mjs
Labels: adhoc, t-tooling, tested

#2775 fix: Simplified RequestQueueV2 implementation
  packages/basic-crawler/src/internals/basic-crawler.ts
  packages/core/src/storages/request_provider.ts
  packages/core/src/storages/request_queue.ts
  packages/core/src/storages/request_queue_v2.ts
  packages/core/test/request-queue/request-queue-v2.test.ts
  packages/types/src/storages.ts
  test/core/storages/request_queue.test.ts
  test/e2e/request-queue-with-concurrency/actor/.actor/actor.json
  test/e2e/request-queue-with-concurrency/actor/.gitignore
  test/e2e/request-queue-with-concurrency/actor/Dockerfile
  test/e2e/request-queue-with-concurrency/actor/main.js
  test/e2e/request-queue-with-concurrency/actor/package.json
  test/e2e/request-queue-with-concurrency/test.mjs
  test/e2e/tools.mjs
Labels: t-tooling, tested

#2837 refactor: set storage object on KV store open
  packages/core/src/storages/key_value_store.ts
  packages/core/src/storages/storage_manager.ts
  test/e2e/kv-open-return-storage-object/actor/.actor/actor.json
  test/e2e/kv-open-return-storage-object/actor/.gitignore
  test/e2e/kv-open-return-storage-object/actor/Dockerfile
  test/e2e/kv-open-return-storage-object/actor/main.js
  test/e2e/kv-open-return-storage-object/actor/package.json
  test/e2e/kv-open-return-storage-object/test.mjs
Labels: adhoc, t-platform, tested

#2833 feat: use native `impit` streaming
  packages/impit-client/package.json
  packages/impit-client/src/index.ts
  yarn.lock
Labels: adhoc, t-tooling

#2848 fix: Make log message in RequestQueue.isFinished more accurate
  packages/core/src/storages/request_queue_v2.ts
Labels: adhoc, t-tooling

#2854 chore: fix failing e2e tests
  test/e2e/cheerio-max-requests/test.mjs
  test/e2e/kv-open-return-storage-object/actor/main.js
  test/e2e/puppeteer-store-pagination-jquery/actor/main.js
  test/e2e/puppeteer-store-pagination/actor/main.js
Labels: adhoc, t-tooling, tested

#2842 feat: Camoufox-based crawler template
  packages/templates/manifest.json
  packages/templates/templates/camoufox-ts/.dockerignore
  packages/templates/templates/camoufox-ts/.gitignore
  packages/templates/templates/camoufox-ts/Dockerfile
  packages/templates/templates/camoufox-ts/README.md
  packages/templates/templates/camoufox-ts/package.json
  packages/templates/templates/camoufox-ts/src/main.ts
  packages/templates/templates/camoufox-ts/src/routes.ts
  packages/templates/templates/camoufox-ts/tsconfig.json
Labels: adhoc, t-tooling

#2863 chore: add `postinstall` script to `camoufox` template
  packages/templates/templates/camoufox-ts/Dockerfile
  packages/templates/templates/camoufox-ts/package.json
Labels: adhoc, t-tooling

#2864 fix: install browser in the `camoufox` template correctly
  packages/templates/templates/camoufox-ts/Dockerfile
Labels: adhoc, t-tooling
