Repository apify/crawlee, pull requests merged in 2025-07, with the labels that each got.

#3042 chore(e2e): make `playwright-multi-run` more stable
  test/e2e/playwright-multi-run/test.mjs
Labels: adhoc, t-tooling, tested

#3043 fix: call `onSkippedRequest` for `AdaptivePlaywrightCrawler.enqueueLinks`
  packages/playwright-crawler/src/internals/adaptive-playwright-crawler.ts
Labels: t-tooling

#3045 feat: add `maxCrawlDepth` crawler option
  packages/basic-crawler/src/internals/basic-crawler.ts
  packages/browser-crawler/src/internals/browser-crawler.ts
  packages/cheerio-crawler/src/internals/cheerio-crawler.ts
  packages/core/src/enqueue_links/enqueue_links.ts
  packages/core/src/enqueue_links/shared.ts
  packages/core/src/request.ts
  packages/jsdom-crawler/src/internals/jsdom-crawler.ts
  packages/linkedom-crawler/src/internals/linkedom-crawler.ts
  test/core/crawlers/basic_crawler.test.ts
  test/core/crawlers/browser_crawler.test.ts
  test/core/crawlers/cheerio_crawler.test.ts
  test/core/storages/request_queue.test.ts
Labels: t-tooling, tested

#3060 fix: retry on blocked status codes in `HttpCrawler`
  packages/http-crawler/src/internals/http-crawler.ts
Labels: t-tooling

#3085 docs: Add link to Python documentation to llms.txt
  website/docusaurus.config.js
  website/package.json
Labels: adhoc, t-web

#3092 docs: switch from pipx to uvx
  website/src/pages/index.js
Labels: adhoc, t-tooling

#3105 chore: don't skip docs build on release
  .github/workflows/release.yml
Labels: adhoc, t-tooling
