Repository apify/crawlee, pull requests merged in 2025-09, with the labels that each got.

#3175 docs: fix search modal styles after docsearch v4 update
  website/docusaurus.config.js
  website/package.json
  website/src/css/custom.css
  website/yarn.lock
Labels: adhoc, t-tooling

#3143 docs: Add Crawlee for Python v1 release blogpost
  website/blog/2025/09-15/img/crawlee_v100.webp
  website/blog/2025/09-15/index.md
Labels: documentation, adhoc, t-tooling

#3180 docs: Update Crawlee Python link and wording
  README.md
Labels: adhoc, t-tooling

#3184 docs: add crawlee for python v1 launch banner
  website/docusaurus.config.js
Labels: t-tooling
