Repository apify/crawlee, pull requests merged in 2025-03, with the labels that each got.

#2865 feat: add `handleCloudflareChallenge` helper
  docs/guides/avoid_blocking.mdx
  docs/guides/avoid_blocking_camoufox.ts
  package.json
  packages/impit-client/src/index.ts
  packages/playwright-crawler/src/internals/utils/playwright-utils.ts
  test/e2e/camoufox-cloudflare/actor/.actor/actor.json
  test/e2e/camoufox-cloudflare/actor/.gitignore
  test/e2e/camoufox-cloudflare/actor/Dockerfile
  test/e2e/camoufox-cloudflare/actor/main.js
  test/e2e/camoufox-cloudflare/actor/package.json
  test/e2e/camoufox-cloudflare/test.mjs
  test/e2e/run.mjs
  website/versioned_docs/version-3.12/guides/avoid_blocking.mdx
  website/versioned_docs/version-3.12/guides/avoid_blocking_camoufox.ts
  yarn.lock
Labels: adhoc, product roadmap, t-tooling, tested

#2868 chore: remove camoufox mentions from v3.12
  website/versioned_docs/version-3.12/guides/avoid_blocking.mdx
  website/versioned_docs/version-3.12/guides/avoid_blocking_camoufox.ts
Labels: adhoc, t-tooling

#2862 feat(website): header and footer design uplift
  website/docusaurus.config.js
  website/src/css/custom.css
  website/src/theme/DocBreadcrumbs/Items/Home/index.js
  website/src/theme/DocBreadcrumbs/Items/Home/styles.module.css
  website/src/theme/Footer/LinkItem/index.js
  website/src/theme/Footer/LinkItem/index.module.css
  website/src/theme/Footer/index.js
  website/src/theme/Footer/index.module.css
  website/src/theme/Logo/index.js
  website/src/theme/Logo/styles.module.css
  website/src/theme/Navbar/Content/index.js
  website/src/theme/Navbar/Content/styles.module.css
  website/src/theme/Navbar/Logo/index.js
  website/src/theme/Navbar/Logo/index.module.css
  website/src/theme/Navbar/MobileSidebar/Header/index.js
  website/src/theme/Navbar/MobileSidebar/Header/index.module.css
  website/src/theme/Navbar/MobileSidebar/Layout/index.js
  website/src/theme/Navbar/MobileSidebar/PrimaryMenu/index.js
  website/src/theme/Navbar/MobileSidebar/index.js
  website/static/img/check.svg
  website/static/img/crawlee-dark.svg
  website/static/img/crawlee-javascript-dark.svg
  website/static/img/crawlee-javascript-light.svg
  website/static/img/crawlee-light.svg
  website/static/img/crawlee-python-dark.svg
  website/static/img/crawlee-python-light.svg
  website/static/img/external-link.svg
  website/static/img/footer-apify-logo.svg
  website/static/img/footer-open-source.svg
  website/static/img/hearth.svg
  website/static/img/menu-arrows.svg
Labels: t-web

#2867 feat(website): search modal design uplift
  website/docusaurus.config.js
  website/src/css/custom.css
Labels: t-web

#2873 docs: add truncation marker to the latest blog post
  website/blog/2025/03-05-superscraper/index.md
Labels: adhoc, t-tooling

#2879 chore: pin playwright to 1.50.1 to fix camoufox template
  package.json
  packages/templates/templates/camoufox-ts/Dockerfile
  packages/templates/templates/camoufox-ts/package.json
  renovate.json
  test/e2e/camoufox-cloudflare/actor/Dockerfile
  test/e2e/camoufox-cloudflare/actor/package.json
  yarn.lock
Labels: adhoc, t-tooling, tested

#2875 docs: Add Crawlee for Python v0.6 release blog post
  website/blog/2025/03-06/img/crawlee_v060.webp
  website/blog/2025/03-06/index.md
Labels: adhoc, t-tooling
