Repository apify/crawlee, pull requests merged in 2025-01, with the labels that each got.

#2796 chore: update docusaurus to v3.7
  website/blog/2024/06-10-creating-a-netflix-show-recommender-using-crawlee-and-react/index.md
  website/package.json
  website/yarn.lock
Labels: adhoc, t-tooling

#2803 fix: destructure `CrawlerRunOptions` before passing them to `addRequests`
  packages/basic-crawler/src/internals/basic-crawler.ts
Labels: t-tooling

#2804 docs: Add Crawlee for Python v0.5 release blog post
  website/blog/2025/01-10/img/import_crawlers.webp
  website/blog/2025/01-10/index.md
  website/blog/authors.yml
Labels: documentation, t-tooling

#2793 docs: more details about different `ProxyConfiguration` options
  docs/guides/proxy_management.mdx
  website/versioned_docs/version-3.12/guides/proxy_management.mdx
Labels: adhoc, t-tooling

#2816 chore(ci): pin Ubuntu 22.04 because of Playwright dependencies
  .github/workflows/check-pr-title.yml
  .github/workflows/docker-images.yml
  .github/workflows/docs.yml
  .github/workflows/release.yml
  .github/workflows/test-ci.yml
  .github/workflows/test-e2e.yml
  .github/workflows/update_new_issue.yml
Labels: adhoc, t-tooling

#2818 chore: fix the `LinkeDOM` e2e test
  test/e2e/linkedom-default-ts/actor/main.ts
Labels: adhoc, t-tooling, tested

#2817 fix: graceful `BasicCrawler` tidy-up on `CriticalError`
  packages/basic-crawler/src/internals/basic-crawler.ts
Labels: t-tooling

#2792 feat: stopping the crawlers gracefully with `BasicCrawler.stop()`
  packages/basic-crawler/src/internals/basic-crawler.ts
  test/e2e/cheerio-stop-resume-ts/actor/.actor/actor.json
  test/e2e/cheerio-stop-resume-ts/actor/.eslintrc.json
  test/e2e/cheerio-stop-resume-ts/actor/.gitignore
  test/e2e/cheerio-stop-resume-ts/actor/Dockerfile
  test/e2e/cheerio-stop-resume-ts/actor/main.ts
  test/e2e/cheerio-stop-resume-ts/actor/package.json
  test/e2e/cheerio-stop-resume-ts/actor/tsconfig.json
  test/e2e/cheerio-stop-resume-ts/test.mjs
Labels: t-tooling, tested

#2787 feat: `impit`-based `HttpClient` implementation
  packages/impit-client/README.md
  packages/impit-client/package.json
  packages/impit-client/src/index.ts
  packages/impit-client/tsconfig.build.json
  packages/impit-client/tsconfig.json
  test/e2e/cheerio-impit-ts/actor/.actor/actor.json
  test/e2e/cheerio-impit-ts/actor/.eslintrc.json
  test/e2e/cheerio-impit-ts/actor/.gitignore
  test/e2e/cheerio-impit-ts/actor/Dockerfile
  test/e2e/cheerio-impit-ts/actor/main.ts
  test/e2e/cheerio-impit-ts/actor/package.json
  test/e2e/cheerio-impit-ts/actor/tsconfig.json
  test/e2e/cheerio-impit-ts/test.mjs
  yarn.lock
Labels: adhoc, t-tooling, tested

#2822 docs: Fix syntax and wording in google maps scraping blog
  website/blog/2024/12-13-scrape-google-maps-using-python/index.md
Labels: adhoc, t-tooling

#2826 docs: hide crawlee for python announcement bar
  website/docusaurus.config.js
Labels: adhoc, t-tooling

#2812 ci: replace `playwright-github-action` with `playwright install --with-deps`
  .github/workflows/release.yml
  .github/workflows/test-ci.yml
  .github/workflows/test-e2e.yml
Labels: adhoc, t-tooling
